version: "3.3"

services:
  # Welcome to nginx on port 8090
  nginx:
    container_name: "nginx-1"
    image: nginx
    ports:
      - "9090:80"
    volumes:
      - "./nginx/index.html:/usr/share/nginx/html/index.html"

  # varnish
  # 7442 is http
  # 7443 is proxy protocol
  varnish:
    container_name: "varnish-1"
    # image: "varnish:6"
    # image: "varnish:6.0.3"
    # image: "varnish:6.0.7-1"
    # image: "emgag/varnish:6.0.7"
    image: "runelangseid/varnish:6.0.7"
    ports:
      - "7442:80"
      - "7443:8443"
    volumes:
      - "./varnish/default.vcl:/etc/varnish/default.vcl:ro"

  # haproxy
  # 8180 is http
  # 8181 contacts varnish using proxy protocol
  haproxy:
    container_name: "haproxy-1"
    image: "haproxy"
    ports:
      - "8180:80"
      - "8181:81"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik-1"
    ports:
      - "680:80"
      - "681:81"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/config:/etc/traefik/config:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/log:/logs:rw
