tcp:
  services:
    varnish:
      loadBalancer:
        proxyProtocol:
          version: 2
        servers:
        - address: "varnish:8443"
    varnishexternal:
      loadBalancer:
        proxyProtocol:
          version: 2
        servers:
        - address: "xxx:8443"

  routers:
    varnish-router:
      rule: "HostSNI(`*`)"
      service: "varnish"
      entrypoints:
        - "proxyprotocol"
      # this makes thing difficult
      # tls: {}

    varnishexternal-router:
      rule: "HostSNI(`*`)"
      service: "varnishexternal"
      entrypoints:
        - "proxyprotocolexternal"

http:
  routers:
    http-router:
      rule: "PathPrefix(`/`)"
      service: "varnish"
      entrypoints:
        - "http"

  services:
    varnish:
      loadBalancer:
        servers:
        - url: "http://varnish:80/"
